### ISSUE TITLE
Sound played two times regardless of preferences

### ISSUE THREAD

**Issue by raffaem** [blackjackshellac/kitchenTimer#52]
In preferences->sound->"play sound" I put "1", but the sound is played 2 times regardless.

Did I misinterpret this option?

**Comment by blackjackshellac** [comment]
Yes, you interpreted the option correctly, no it doesn't work as intended when set to one.

Are you using the github or the release version?

**Comment by raffaem** [comment]
I am using the release version

**Comment by blackjackshellac** [comment]
This is now fixed on github.

**Comment by blackjackshellac** [comment]
BTW @raffaem, fix is now updated at gnome.extensions.org

**Comment by raffaem** [comment]
Thanks! 🤠

**Comment by raffaem** [comment]
I don't see updates on extensions.gnome.org

I have version 17

**Comment by blackjackshellac** [comment]
That's the version with the fix.
