### ISSUE TITLE
Not working after update on F34

### ISSUE THREAD

**Issue by lasersocks** [blackjackshellac/kitchenTimer#61]
Hi,

I am no longer able to use this extension after updating it on a stock F34 install.

![Screenshot from 2021-05-06 09-01-42](https://user-images.githubusercontent.com/5710017/117302591-ce2f8b00-ae49-11eb-9251-37cc0aca7dcc.png)

**Comment by blackjackshellac** [comment]
I just updated an F34 system using the gnome extensions app.  Did you try logging out and back in again, (or restarting the shell if you're running Xorg)?

**Comment by lasersocks** [comment]
After a restart I was able to install it again.

**Comment by raffaem** [comment]
Same exact problem.

Update broke the extension. Gives error after install.

Remove the extension. Reboot. Re-install it and it works now

**Comment by blackjackshellac** [comment]
I find that many extension updates fail to cleanly update these days.  I *think* it has to do with changes to changes to the settings schema.  Restarting the shell (on X do Alt-F2, r) fixes the problems when updating on extensions.gnome.org.  If you're running wayland I think I'd have to either reboot or logout and login again.  I suspect this is why the gnome-extensions-app, when automagically updating extensions, suggests logging out to update.  Next time I get the error I will see if I can fix it without rebooting or logging out/in.
