### ISSUE TITLE
white rectangle after name

### ISSUE THREAD

**Issue by meridius** [blackjackshellac/kitchenTimer#63]
Not sure why, but I can see white rectangle after the timer name.

![obrazek](https://user-images.githubusercontent.com/372431/119367067-df81ef80-bcb1-11eb-874d-d836386d805d.png)

**Comment by blackjackshellac** [comment]
It's a unicode character that your platform doesn't support, I guess.

**Comment by blackjackshellac** [comment]
Mine looks like this 
![image](https://user-images.githubusercontent.com/825403/119387145-8789bf80-bc96-11eb-918f-52a48a044c97.png)

I can change it if it's a problem.

**Comment by blackjackshellac** [comment]
Unicode U+2B9A

What distro and gnome shell version are you using?

**Comment by meridius** [comment]
I can add the smileys no problem.
![obrazek](https://user-images.githubusercontent.com/372431/119404135-ad878200-bcdf-11eb-9f5c-a6cc7d58c114.png)

Adding the U+2B9A as "bar ⮚" shows this:
![obrazek](https://user-images.githubusercontent.com/372431/119404298-e889b580-bcdf-11eb-86fc-77cbff7a18c1.png)

I'm using Arch and Gnome Shell 40.1.0 with Cantarell as a default font. As I can see it has poor Unicode support despite it being the default font in Gnome. https://en.wikipedia.org/wiki/Cantarell_(typeface)#Criticism
It is maybe for consideration whether you really need to have that Unicode char there, given many users will have this default font, and aren't able to remove the Unicode char.

**Comment by blackjackshellac** [comment]
Strange, Cantarell is the default font on fedora 34 too.

/usr/share/fonts/cantarell/Cantarell-Regular.otf version 0.301

Obviously not a huge issue, so I have no objection to removing it.

**Comment by blackjackshellac** [comment]
thanks for the pull request :)
